sudo: required

language: c

services:
- docker

env:
- OVERSION="3.8"
- OVERSION="4.0"
- OVERSION="4.2"

before_install:
- docker build -f dockerfiles/octave${OVERSION}/Dockerfile . -t trusty/r-octave${OVERSION}
- docker run -it -d --name builder trusty/r-octave${OVERSION} /bin/sh
- docker ps -a

script:
- docker exec -it builder /bin/sh -c "cd /root/repo; R CMD build ."
- docker exec -it builder /bin/sh -c "cd /root/repo; R CMD check \"${PKG_TARBALL}\" --as-cran --no-manual; echo CHECK_RET=\$? >> /root/env_vars"
- CHECK_RET=$(docker exec builder /bin/sh -c ". /root/env_vars; echo \$CHECK_RET")
- docker cp builder:/root/repo/${PKG_TARBALL} .
