sudo: required

language: c

services:
- docker

env:
- OVERSION="3.8"
- OVERSION="4.0"
- OVERSION="4.2"

before_install:
- docker build -f dockerfiles/octave${OVERSION}/Dockerfile . -t trusty/r-octave${OVERSION}
- docker run -d -p 127.0.0.1:80:4567 trusty/r-octave${OVERSION} /bin/sh -c "cd /root/repo"
- docker ps -a

script:
- docker run trusty/r-octave${OVERSION} /bin/sh -c "cd /root/repo; R CMD build ."
